spring:
  application:
    name: eureka-server1
    
server:
  port: 1002
    
eureka:
  instance:
    hostname: localhost
  client:
  
    #register-with-eureka配置是否注册自己，在单节点中因为自己本身就是服务注册中心，所以不需要注册自己。（默认为true）
    # register-with-eureka: false
    #fetch-registr配置是否从配置中心获取注册的服务，在单节点中因为本身只负责服务治理，所以不需要抓取注册的服务。（默认为true）
    # fetch-registry: false
    
    service-url:
      # 若是单节点服务注册中心，此值代表服务提供者的注册地址；为高可用多服务注册中心时，此值配置其它注册中心的注册地址
      defaultZone: http://localhost:1001/eureka/