server:
  port: 10001
  
spring:
  application:
    name: Oauth2-Resource-Server
    
security:
  oauth2:
    resource:
      id: oauth2-resource-server
      user-info-uri: http://localhost:10000/auth/user
      prefer-token-info: true
      token-info-uri: http://localhost:10000/auth/oauth/check_token
      
logging:
  level:
    org.springframework.security: debug
    