# Spring Boot默认读取application.properties或者application.yml文件中的配置项
# 默认会在以下路径中加载配置文件：
#   1. 当前路径的/config子目录下
#   2. 当前目录
#   3. classpath的/config子目录下
#   4. classpath根目录下
# 如果配置文件的名称不为application，则可以使用spring.config.name指定其文件名称；或者使用spring.config.location指定具体文件路径


# 不同的profile指定的环境，配置文件默认加载application-{profile}.properties的约定名称


    
    
# 指定运行环境
spring:
  profiles:
    active: dev
      