server: 
  port: 10002
  
spring:
  application:
    name: Oauth2-Client
    
security:
  oauth2:
    client:
      client-id: client-by-authorization_code
      client-secret: xingkelaochen
      user-authorization-uri: http://localhost:10000/auth/oauth/authorize
      access-token-uri: http://localhost:10000/auth/oauth/token
      clientAuthenticationScheme: form
      scope:
        trust
    resource: 
      # prefer-token-info: false
      user-info-uri: http://localhost:10000/auth/user
      # token-info-uri: http://localhost:10000/auth/oauth/check_token
      
logging:
  level:
    org.springframework.security: debug