spring:
  application:
    name: Spring-Boot-Service
    
  profiles:
    #active: service1
    active: service2
    
  zipkin: 
    base-url: http://localhost:7000
    
  sleuth:
    sampler:
      # Sleuth链路跟踪抽样百分比
      percentage: 1
  
eureka:
  client:
    service-url:
      # 将服务注册到注册服务集群的多个注册中心中，以,分隔
      # defaultZone: http://eureka-server1:1001/eureka/,http://eureka-server2:1002/eureka/
      # 若有多个服务提供者，分别注册到集群中的单个注册中心中时，将会将注册信息转发给其他注册中心。（服务同步）
      defaultZone: http://eureka-server1:1001/eureka/
  instance:
  # 由服务提供者向注册中心发送心跳进行（服务续约）
    # 服务续约任务调用的间隔时间，默认30秒
    lease-renewal-interval-in-seconds: 30
    # 服务失效时间，默认90秒
    lease-expiration-duration-in-seconds: 90
    
    # 实例元数据配置
    metadata-map:
      # 指定实例zone属性
      zone: xingkelaochen
      
debug: true